export const conversationList = [
    {
      id: 1,
      conversationType: "GROUP",
      conversationName: "Family",
      createdDate: 1633024800,
    },
    {
      id: 2,
      conversationType: "PRIVATE",
      contacts: [{ name: "Alice" }],
      creatorName: "Bob",
      createdDate: 1633035600,
    },
    {
      id: 3,
      conversationType: "GROUP",
      conversationName: "Work",
      createdDate: 1633046400,
    },
    {
      id: 4,
      conversationType: "PRIVATE",
      contacts: [{ name: "Charlie" }],
      creatorName: "David",
      createdDate: 1633057200,
    },
    {
      id: 5,
      conversationType: "GROUP",
      conversationName: "Friends",
      createdDate: 1633068000,
    },
    {
      id: 6,
      conversationType: "PRIVATE",
      contacts: [{ name: "Eve" }],
      creatorName: "Frank",
      createdDate: 1633078800,
    },
    {
      id: 7,
      conversationType: "GROUP",
      conversationName: "Book Club",
      createdDate: 1633089600,
    },
    {
      id: 8,
      conversationType: "PRIVATE",
      contacts: [{ name: "Grace" }],
      creatorName: "Heidi",
      createdDate: 1633100400,
    },
    {
      id: 9,
      conversationType: "GROUP",
      conversationName: "Gaming Buddies",
      createdDate: 1633111200,
    },
    {
      id: 10,
      conversationType: "PRIVATE",
      contacts: [{ name: "Ivan" }],
      creatorName: "Judy",
      createdDate: 1633122000,
    },
    {
      id: 11,
      conversationType: "GROUP",
      conversationName: "Travel Plans",
      createdDate: 1633132800,
    },
    {
      id: 12,
      conversationType: "PRIVATE",
      contacts: [{ name: "Mallory" }],
      creatorName: "Niaj",
      createdDate: 1633143600,
    },
    {
      id: 13,
      conversationType: "GROUP",
      conversationName: "Study Group",
      createdDate: 1633154400,
    },
    {
      id: 14,
      conversationType: "PRIVATE",
      contacts: [{ name: "Olivia" }],
      creatorName: "Peggy",
      createdDate: 1633165200,
    },
    {
      id: 15,
      conversationType: "GROUP",
      conversationName: "Sports Team",
      createdDate: 1633176000,
    },
    {
      id: 16,
      conversationType: "PRIVATE",
      contacts: [{ name: "Sybil" }],
      creatorName: "Trent",
      createdDate: 1633186800,
    },
    {
      id: 17,
      conversationType: "GROUP",
      conversationName: "Music Band",
      createdDate: 1633197600,
    },
    {
      id: 18,
      conversationType: "PRIVATE",
      contacts: [{ name: "Victor" }],
      creatorName: "Wendy",
      createdDate: 1633208400,
    },
    {
      id: 19,
      conversationType: "GROUP",
      conversationName: "Cooking Club",
      createdDate: 1633219200,
    },
    {
      id: 20,
      conversationType: "PRIVATE",
      contacts: [{ name: "Xavier" }],
      creatorName: "Yvonne",
      createdDate: 1633230000,
    }
  ];


  export const MessageData = [
    {
      id: 1,
      conversationId: 1,
      senderId: 2,
      senderName: "Alice Hook",
      content: "Hey everyone! How's it going?",
      timestamp: 1633028400,
    },
    {
      id: 2,
      conversationId: 1,
      senderId: 3,
      senderName: "Bob Smith",
      content: "Hi! I'm doing well, thanks for asking.",
      timestamp: 1633028460,
    },
    {
      id: 3,
      conversationId: 2,
      senderId: 4,
      senderName: "Charlie Brown",
      content: "Are we still on for lunch tomorrow?",
      timestamp: 1633032000,
    },
    {
      id: 4,
      conversationId: 2,
      senderId: 5,
      senderName: "David Johnson",
      content: "Yes, looking forward to it!",
      timestamp: 1633032060,
    },
    {
      id: 5,
      conversationId: 3,
      senderId: 6,
      senderName: "Eve Adams",
      content: "Don't forget about the meeting at 3 PM.",
      timestamp: 1633042800,
    },
    {
      id: 6,
      conversationId: 3,
      senderId: 7,
      senderName: "Frank Miller",
      content: "Thanks for the reminder!",
      timestamp: 1633042860,
    },
    {
      id: 7,
      conversationId: 4,
      senderId: 8,
      senderName: "Grace Lee",
      content: "Can you send me the report by end of day?",
      timestamp: 1633050000,
    },
    {
      id: 8,
      conversationId: 4,
      senderId: 9,
      senderName: "David Wilson",
      content: "Sure, I'll have it ready.",
      timestamp: 1633050060,
    },
    {
      id: 9,
      conversationId: 5,
      senderId: 10,
      senderName: "Heidi Clark",
      content: "Who's up for a movie night this weekend?",
      timestamp: 1633060800,
    },
    {
      id: 10,
      conversationId: 5,
      senderId: 11,
      senderName: "Ivan Davis",
      content: "Count me in!",
      timestamp: 1633060860,
    },
  ]